version: "3"

services:
  contender-db:
    image: mariadb
    container_name: contender-db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=MzF46TqoAug6Y
      - MYSQL_DATABASE=contender
      - MYSQL_USER=contender
      - MYSQL_PASSWORD=7SI6dsa5GHB7f
    expose:
      - 3306
    ports:
      - 7912:3306

  contender-php:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    container_name: contender-php
    volumes:
      - ./php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./app:/var/www/app
    depends_on:
      - contender-db
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"

  contender-web:
    image: nginx:latest
    container_name: contender-web
    volumes:
      - ./nginx/back.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/app
    depends_on:
      - contender-db
      - contender-php
    expose:
      - 80
      - 443
    ports:
      - 80:80

volumes:
  db_data:
